version: '3.8'

services:
  server:
    image: python-server-img 
    container_name: python-server  
    volumes:
      - /run/udev:/run/udev:ro 
      - ./shared_vol:/tmp/annotated_output  
    ports:
      - "8000:8000"  
    networks:
      - app-network 
    restart: always 
    privileged: true 
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "-m", "src.main.scripts.run_server", "--port", "8000"]

  webapp:
    image: node-webapp-img 
    container_name: node-webapp
    ports:
      - "3000:3000"  
    networks:
      - app-network 
    restart: always 
    environment:
      - SERVER_URL=http://python-server:8000  
    command: ["node", "app.js"]  

networks:
  app-network:
    driver: bridge  
