version: '3.8'

services:
  server:
    build:
      context: ./server  # Path to the server directory
      dockerfile: Dockerfile
    container_name: python-server  # Assign a name to the server container
    volumes:
      - /run/udev:/run/udev:ro  # Map /run/udev for privileged access
      - ./shared_vol:/tmp/annotated_output  # Shared volume for output
    ports:
      - "8000:8000"  # Map server port to host
    networks:
      - app-network  # Attach server to a shared network
    restart: always  # Restart the container on failure
    privileged: true  # Allow access to hardware resources
    environment:
      - PYTHONUNBUFFERED=1  # Avoid buffering Python output

  webapp:
    build:
      context: ./webapp  # Path to the web app directory
      dockerfile: Dockerfile
    container_name: node-webapp  # Assign a name to the web app container
    ports:
      - "3000:3000"  # Map web app port to host
    networks:
      - app-network  # Attach web app to a shared network
    restart: always  # Restart the container on failure
    environment:
      - SERVER_URL=http://python-server:8000  # URL to access the server app

networks:
  app-network:
    driver: bridge  # Create a bridge network for inter-container communication
