version: '3.8'

services:
  server:
    image: python-server-img 
    container_name: python-server  
    volumes:
      - /run/udev:/run/udev:ro 
      - ./shared_vol:/tmp/annotated_output  
    ports:
      - "8000:8000"  
    networks:
      - app-network 
    restart: always 
    privileged: true 
    environment:
      - PYTHONUNBUFFERED=1  # Avoid buffering Python output
    command: ["python3", "-m", "src.main.scripts.run_server", "--port", "8000"]  # Replace with the Python command you want to run

  webapp:
    image: node-webapp-img  # Use the prebuilt webapp image
    container_name: node-webapp  # Assign a name to the web app container
    ports:
      - "3000:3000"  # Map web app port to host
    networks:
      - app-network 
    restart: always 
    environment:
      - SERVER_URL=http://python-server:8000  # URL to access the server app
    command: ["node", "app.js"]  

networks:
  app-network:
    driver: bridge  
